"""add_currency_to_advertiser

Revision ID: 27cce23e7b84
Revises: 8b45c432fb11
Create Date: 2026-02-09 20:10:28.405049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cce23e7b84'
down_revision: Union[str, Sequence[str], None] = '8b45c432fb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisers', sa.Column('currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisers', 'currency')
    # ### end Alembic commands ###
