"""Add indices for stats aggregation

Revision ID: 5bd9ae5b5d0b
Revises: e719d907afad
Create Date: 2026-01-14 14:51:36.538943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd9ae5b5d0b'
down_revision: Union[str, Sequence[str], None] = 'e719d907afad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customer_events_event_type'), 'customer_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_customer_events_timestamp'), 'customer_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_events_timestamp'), table_name='customer_events')
    op.drop_index(op.f('ix_customer_events_event_type'), table_name='customer_events')
    # ### end Alembic commands ###
