"""add_influencer_model

Revision ID: 7eecbb3b3b83
Revises: 45764ae62158
Create Date: 2025-12-21 13:35:25.361437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eecbb3b3b83'
down_revision: Union[str, Sequence[str], None] = '45764ae62158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('social_handle', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencers_email'), 'influencers', ['email'], unique=True)
    op.create_index(op.f('ix_influencers_id'), 'influencers', ['id'], unique=False)
    op.create_index(op.f('ix_influencers_name'), 'influencers', ['name'], unique=False)
    op.create_table('campaign_influencers',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'influencer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_influencers')
    op.drop_index(op.f('ix_influencers_name'), table_name='influencers')
    op.drop_index(op.f('ix_influencers_id'), table_name='influencers')
    op.drop_index(op.f('ix_influencers_email'), table_name='influencers')
    op.drop_table('influencers')
    # ### end Alembic commands ###
