"""add_revenue_share_columns

Revision ID: 8b45c432fb11
Revises: 2817f8625652
Create Date: 2026-02-07 13:52:51.191944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b45c432fb11'
down_revision: Union[str, Sequence[str], None] = '2817f8625652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_influencers', sa.Column('revenue_share_value', sa.Float(), nullable=True))
    op.add_column('campaign_influencers', sa.Column('revenue_share_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_influencers', 'revenue_share_type')
    op.drop_column('campaign_influencers', 'revenue_share_value')
    # ### end Alembic commands ###
