"""Add tracking links and click events

Revision ID: acc45cebb39c
Revises: cb4b099be6c4
Create Date: 2025-12-30 16:53:19.893550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc45cebb39c'
down_revision: Union[str, Sequence[str], None] = 'cb4b099be6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('destination_url', sa.String(length=500), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=True),
    sa.Column('cpc_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_links_id'), 'tracking_links', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_links_short_code'), 'tracking_links', ['short_code'], unique=True)
    op.create_table('click_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_link_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('referer', sa.String(length=500), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['tracking_link_id'], ['tracking_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_events_id'), 'click_events', ['id'], unique=False)
    op.create_index(op.f('ix_click_events_timestamp'), 'click_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_events_timestamp'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_id'), table_name='click_events')
    op.drop_table('click_events')
    op.drop_index(op.f('ix_tracking_links_short_code'), table_name='tracking_links')
    op.drop_index(op.f('ix_tracking_links_id'), table_name='tracking_links')
    op.drop_table('tracking_links')
    # ### end Alembic commands ###
